import Head from 'next/head';import { Header } from '../Header';
import { Footer } from '../Footer';
export const Layout = ({ title, children, className }) => {
  return (
    <div className={`mx-auto max-w-screen-md lg:max-w-screen-lg ${className}`}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  );
};
