import Head from 'next/head';
export const Layout = ({ title, children, className }) => {
  return (
    <div className={className}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </div>
  );
};
